### PR TITLE
Preliminary Kerberos support

### PR DESCRIPTION
**Pull request by fred4freedom**

### CODE REVIEW

**Comment by chrissng** [comment]
Might be important:
- `kinit` for airflow scheduler, sqoop command
- Spark with Kerberos: https://www.cloudera.com/documentation/enterprise/5-10-x/topics/cm_sg_yarn_long_jobs.html

**Comment by fred4freedom** [comment]
kinit is installed with the client package. user is expected to put in the principal and keytab subsequently when they want to use it with kerberos (instructions in README)

**Review by chrissng — APPROVED** [review]
LGTM. But more work might be needed for Sqoop and Airflow

**Comment by chrissng** [comment]
Cloudera Kerberos principals and keytabs https://www.cloudera.com/documentation/enterprise/5-10-x/topics/cm_sg_principal_keytab.html

**Pull request merged**
